/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Org.EduardoAgustin.Ventanas;

/**
 *
 * @author Eduardo Agustin
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setTitle("Menu Principal");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setBounds(385, 115, 504, 530);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Top5 = new javax.swing.JButton();
        Burbuja = new javax.swing.JButton();
        Iniciar = new javax.swing.JButton();
        Acercadealgo = new javax.swing.JButton();
        Bai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Top5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        Top5.setText("Top 5 QuickSort");
        getContentPane().add(Top5);
        Top5.setBounds(100, 100, 300, 33);

        Burbuja.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        Burbuja.setText("Top 5 BubbleSort");
        getContentPane().add(Burbuja);
        Burbuja.setBounds(100, 170, 300, 33);

        Iniciar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        Iniciar.setText("Iniciar Juego");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });
        getContentPane().add(Iniciar);
        Iniciar.setBounds(100, 250, 300, 33);

        Acercadealgo.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        Acercadealgo.setText("Acerca de...");
        getContentPane().add(Acercadealgo);
        Acercadealgo.setBounds(100, 320, 300, 33);

        Bai.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        Bai.setText("Salir");
        Bai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaiActionPerformed(evt);
            }
        });
        getContentPane().add(Bai);
        Bai.setBounds(100, 430, 300, 33);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Galaga/de3a4e5b0a5d4194-espacio-tumblr-gif-10-gif-images-download.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaiActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BaiActionPerformed

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
       Galaga gal = new Galaga();
       gal.setVisible(true);
       Menu.this.setVisible(false);
    }//GEN-LAST:event_IniciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acercadealgo;
    private javax.swing.JButton Bai;
    private javax.swing.JButton Burbuja;
    private javax.swing.JButton Iniciar;
    private javax.swing.JButton Top5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
